server:
    port: 8080

keycloak:
    realm: prenRealm
    auth-server-url: http://localhost:9000/auth
    ssl-required: external
    resource: prenPalestra
    #credentials.secret: b87d573f-fdf5-41a3-9525-94cb01baff09
    credentials.secret: ab5fa819-7aad-4b5a-ae6f-bd708132a53b
    use-resource-role-mappings: true
    keycloak.bearer-only: true